# Generated by Django 3.0.5 on 2020-04-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('DateOfBirth', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=25)),
                ('Phone', models.CharField(max_length=10)),
                ('Education', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'loginform',
            },
        ),
    ]
